{% set version = '0.5.8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggnetwork
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggnetwork_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggnetwork/ggnetwork_{{ version }}.tar.gz
  sha256: a8c7c19a2bafce898c95d0b2401ef052925db57b85058c7203f0122b3af7bbbd

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=2.0.0
    - r-ggrepel >=0.5
    - r-igraph
    - r-network
    - r-sna
  run:
    - r-base
    - r-ggplot2 >=2.0.0
    - r-ggrepel >=0.5
    - r-igraph
    - r-network
    - r-sna

test:
  commands:
    - $R -e "library('ggnetwork')"           # [not win]
    - "\"%R%\" -e \"library('ggnetwork')\""  # [win]

about:
  home: https://github.com/briatte/ggnetwork
  license: GPL-3
  summary: Geometries to plot network objects with 'ggplot2'.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggnetwork
# Type: Package
# Title: Geometries to Plot Networks with 'ggplot2'
# Description: Geometries to plot network objects with 'ggplot2'.
# Version: 0.5.8
# Date: 2020-02-06
# Maintainer: Francois Briatte <f.briatte@gmail.com>
# Authors@R: c( person("Francois", "Briatte", email = "f.briatte@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-6494-9774")), person("Micha", "Bojanowski", role = "ctb", comment = c(ORCID = "0000-0001-7503-852X")), person("Mickael", "Canouil", role = "ctb", comment = c(ORCID = "0000-0002-3396-4549")), person("Zachary", "Charlop-Powers", role = "ctb", comment = c(ORCID = "0000-0001-8816-4680")), person("Jacob C.", "Fisher", role = "ctb", comment = c(ORCID = "0000-0003-0299-0346")), person("Kipp", "Johnson", role = "ctb", comment = c(ORCID = "0000-0002-5102-741X")), person("Tyler", "Rinker", role = "ctb") )
# License: GPL-3
# URL: https://github.com/briatte/ggnetwork
# BugReports: https://github.com/briatte/ggnetwork/issues
# Depends: R (>= 3.5), ggplot2 (>= 2.0.0)
# Imports: ggrepel (>= 0.5), network, igraph, sna, utils
# Suggests: knitr, testthat
# Collate: 'utilities.R' 'fortify-igraph.R' 'fortify-network.R' 'geom-nodes.R' 'geom-edges.R' 'ggnetwork.R'
# VignetteBuilder: knitr
# RoxygenNote: 7.0.2
# Encoding: UTF-8
# LazyData: true
# NeedsCompilation: no
# Packaged: 2020-02-12 15:56:15 UTC; fr
# Author: Francois Briatte [aut, cre] (<https://orcid.org/0000-0001-6494-9774>), Micha Bojanowski [ctb] (<https://orcid.org/0000-0001-7503-852X>), Mickael Canouil [ctb] (<https://orcid.org/0000-0002-3396-4549>), Zachary Charlop-Powers [ctb] (<https://orcid.org/0000-0001-8816-4680>), Jacob C. Fisher [ctb] (<https://orcid.org/0000-0003-0299-0346>), Kipp Johnson [ctb] (<https://orcid.org/0000-0002-5102-741X>), Tyler Rinker [ctb]
# Repository: CRAN
# Date/Publication: 2020-02-12 17:00:02 UTC
