travis:
  secure:
    BINSTAR_TOKEN: DWa4aC7jf4MFbZ4N9hb8IwgzOb2ksI3nWr48ILRvzs8AFA+5m4PcGdYSbtFitC9qhE2ytdaXIfbPrASScuqOp8bjPOl7aiCLxdj4G1ipnmZD+ys87S5KLjF9kFKSfWU+tcz49uiRtYwo1fSEVhjW3enPzzQoTgOjFcShoRS+bnc2vr7Jh42oXsxvCLUNi0AE+5LyCM65LcO/ZHQrEh5AehVWesPPDaCwn7yFoboG704T0EKWdpPby+dzYs73+/aVmv+auKMQDKCQDntd71bYwuyTWtuhNq+XL2vnEEvLDOt/1a1cJYJNtsg9255vSLUV2fFMWgk3bv4B7c0+wL9YwItjLmtCm2mFh3czJcZYBu8VzevRqAhaHIXWN5c9RXD4rW0CFbyAe2iqBmlcnI95v9LF49ks9lgMvsrvneAppM1kksQy3fJGapBA5kbP5j7vhvrAOLr0VkChIGTyM55IbIa4NJmV9brHSg9fxln5CNp5jxvS8mMCVtdMrCQkDAt+wI933ME2Z+YMzZbreGKDM+BkgD37M3MvJLPTSJPFm6M2zA9JPwDkBBnXTRSWN+Pbm+jMwYN2EIufNlmT2LdlOlfSHv8VbDLvPn4q0G8zzpx5emlCI4YeD7qKdUh3XLqzPPc/CtydfJoVPzQbX6XLnOs+VJFWRZPFK/lThSr1bn4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
